(function(global) {
  const ENEMY_CATALOG = {
  "miniImp": {
    "displayName": "Imp",
    "assetFolder": "Mini Imp",
    "assetBaseName": "Mini Imp",
    "health": 10,
    "maxHealth": 10,
    "damage": 5,
    "speed": 120,
    "baseRadius": 8,
    "scale": 4,
    "attackBonus": 18,
    "cooldown": 0.9,
    "score": 18,
    "ranged": false,
    "projectileType": null,
    "preferEdges": false,
    "desiredRange": 32,
    "projectileCooldown": 0.9,
    "bossTier": 0,
    "preferredTarget": "player",
    "specialBehavior": [
      "mini",
      "popcorn",
      "closestAny",
      "swarmable"
    ],
    "swarmSpacing": 0.1
  },
  "miniImpLevel2": {
    "displayName": "Imp Lieutenant",
    "assetFolder": "Mini Imp",
    "assetBaseName": "Mini Imp",
    "health": 20,
    "maxHealth": 20,
    "damage": 10,
    "speed": 100,
    "baseRadius": 10,
    "scale": 4.5,
    "attackBonus": 20,
    "cooldown": 0.9,
    "score": 36,
    "ranged": false,
    "projectileType": null,
    "preferEdges": false,
    "desiredRange": 36,
    "projectileCooldown": 0.9,
    "bossTier": 0,
    "preferredTarget": "player",
    "specialBehavior": [
      "mini",
      "elite",
      "closestAny",
      "swarmable",
      "popcorn"
    ],
    "tintColor": "#7ec6ff",
    "tintIntensity": 0.75,
    "swarmSpacing": 0.1
  },
  "miniFireImp": {
    "displayName": "Fire Imp",
    "assetFolder": "Mini Fire Imp",
    "assetBaseName": "Mini Fire Imp",
    "health": 45,
    "maxHealth": 45,
    "damage": 5,
    "speed": 100,
    "baseRadius": 12,
    "scale": 5,
    "attackBonus": 20,
    "cooldown": 1,
    "score": 45,
    "ranged": true,
    "projectileType": "miniTrident",
    "preferEdges": true,
    "desiredRange": 360,
    "projectileCooldown": 1.6,
    "bossTier": 0,
    "preferredTarget": "player",
    "specialBehavior": [
      "mini",
      "projectile",
      "closestAny"
    ]
  },
  "miniDemoness": {
    "displayName": "Demoness",
    "assetFolder": "Mini Demoness",
    "assetBaseName": "Mini Demoness",
    "health": 45,
    "maxHealth": 45,
    "damage": 5,
    "speed": 100,
    "baseRadius": 12,
    "scale": 5.8,
    "attackBonus": 24,
    "cooldown": 1.2,
    "score": 52,
    "ranged": false,
    "projectileType": null,
    "preferEdges": false,
    "desiredRange": 60,
    "projectileCooldown": 1.2,
    "bossTier": 0,
    "preferredTarget": "player",
    "specialBehavior": [
      "mini",
      "closestAny"
    ]
  },
  "miniClawedDemon": {
    "displayName": "Clawed Demon",
    "assetFolder": "Mini Clawed Demon",
    "assetBaseName": "Mini Clawed Demon",
    "health": 45,
    "maxHealth": 45,
    "damage": 15,
    "speed": 100,
    "baseRadius": 12,
    "scale": 3.5,
    "attackBonus": 24,
    "cooldown": 1.3,
    "score": 55,
    "ranged": false,
    "projectileType": null,
    "preferEdges": false,
    "desiredRange": 70,
    "projectileCooldown": 1.3,
    "bossTier": 0,
    "preferredTarget": "player",
    "specialBehavior": [
      "mini",
      "closestAny",
      "swarmable"
    ],
    "swarmSpacing": 0.5
  },
  "miniHighDemon": {
    "displayName": "High Demon",
    "assetFolder": "Mini High Demon",
    "assetBaseName": "Mini High Demon",
    "health": 450,
    "maxHealth": 450,
    "damage": 5,
    "speed": 40,
    "baseRadius": 14,
    "scale": 5.6,
    "attackBonus": 36,
    "cooldown": 1.8,
    "score": 180,
    "ranged": false,
    "projectileType": null,
    "preferEdges": false,
    "desiredRange": 110,
    "projectileCooldown": 1.8,
    "bossTier": 2,
    "preferredTarget": "player",
    "specialBehavior": [
      "mini",
      "boss",
      "closestAny"
    ]
  },
  "miniDemonTormentor": {
    "displayName": "Demon Tormentor",
    "assetFolder": "Mini Demon Tormentor",
    "assetBaseName": "Mini Demon Tormentor",
    "health": 450,
    "maxHealth": 450,
    "damage": 5,
    "speed": 50,
    "baseRadius": 14,
    "scale": 7,
    "attackBonus": 34,
    "cooldown": 1.8,
    "score": 240,
    "ranged": false,
    "projectileType": null,
    "preferEdges": false,
    "desiredRange": 130,
    "projectileCooldown": 1.8,
    "bossTier": 2,
    "preferredTarget": "player",
    "specialBehavior": [
      "mini",
      "boss",
      "closestAny",
      "swarmable"
    ],
    "swarmSpacing": 1
  },
  "miniDemonLord": {
    "displayName": "Demon Lord",
    "assetFolder": "Mini Demon Lord",
    "assetBaseName": "Mini Demon Lord",
    "health": 600,
    "maxHealth": 600,
    "damage": 5,
    "speed": 35,
    "baseRadius": 16,
    "scale": 6.8,
    "attackBonus": 40,
    "cooldown": 1.5,
    "score": 320,
    "ranged": false,
    "projectileType": null,
    "preferEdges": false,
    "desiredRange": 140,
    "projectileCooldown": 1.5,
    "bossTier": 3,
    "preferredTarget": "player",
    "specialBehavior": [
      "mini",
      "boss",
      "heavy",
      "closestAny"
    ]
  },
  "miniDemonFireThrower": {
    "displayName": "Demon Fire Thrower",
    "assetFolder": "Mini Demon Fire Thrower",
    "assetBaseName": "Mini Demon Fire Thrower",
    "health": 45,
    "maxHealth": 45,
    "damage": 5,
    "speed": 100,
    "baseRadius": 12,
    "scale": 4.8,
    "attackBonus": 24,
    "cooldown": 1.9,
    "score": 65,
    "ranged": false,
    "projectileType": "miniTrident",
    "preferEdges": true,
    "desiredRange": 420,
    "projectileCooldown": 2,
    "bossTier": 1,
    "preferredTarget": "player",
    "specialBehavior": [
      "mini",
      "closestAny",
      "swarmable"
    ],
    "swarmSpacing": 1
  },
  "miniDemonFireKeeper": {
    "displayName": "Demon Fire Keeper",
    "assetFolder": "Mini Demon Fire Keeper",
    "assetBaseName": "Mini Demon Fire Keeper",
    "health": 45,
    "maxHealth": 45,
    "damage": 5,
    "speed": 100,
    "baseRadius": 12,
    "scale": 4,
    "attackBonus": 24,
    "cooldown": 1.6,
    "score": 70,
    "ranged": false,
    "projectileType": "miniTrident",
    "preferEdges": true,
    "desiredRange": 420,
    "projectileCooldown": 2.4,
    "bossTier": 1,
    "preferredTarget": "player",
    "specialBehavior": [
      "mini",
      "closestAny"
    ],
    "swarmSpacing": 0.1
  },
  "miniSuccubus": {
    "displayName": "Succubus",
    "assetFolder": "Mini Succubus",
    "assetBaseName": "Mini Succubus",
    "health": 45,
    "maxHealth": 45,
    "damage": 5,
    "speed": 125,
    "baseRadius": 12,
    "scale": 4.8,
    "attackBonus": 26,
    "cooldown": 1.3,
    "score": 75,
    "ranged": true,
    "projectileType": "arrow",
    "preferEdges": true,
    "desiredRange": 360,
    "projectileCooldown": 1.8,
    "bossTier": 1,
    "preferredTarget": "player",
    "specialBehavior": [
      "mini",
      "ranged",
      "closestAny"
    ]
  },
  "miniSkeleton": {
    "displayName": "Skeleton",
    "assetFolder": "Mini Skeleton",
    "assetBaseName": "Mini Skeleton",
    "health": 15,
    "maxHealth": 15,
    "damage": 5,
    "speed": 110,
    "baseRadius": 10,
    "scale": 3.8,
    "attackBonus": 20,
    "cooldown": 1.4,
    "score": 60,
    "ranged": false,
    "projectileType": null,
    "preferEdges": true,
    "desiredRange": 50,
    "projectileCooldown": 1.4,
    "bossTier": 0,
    "preferredTarget": "player",
    "specialBehavior": [
      "mini",
      "closestAny"
    ]
  },
  "miniSkeletonArcher": {
    "displayName": "Skeleton Archer",
    "assetFolder": "Mini Skeleton Archer",
    "assetBaseName": "Mini Skeleton Archer",
    "health": 45,
    "maxHealth": 45,
    "damage": 5,
    "speed": 115,
    "baseRadius": 10,
    "scale": 4,
    "attackBonus": 20,
    "cooldown": 1.5,
    "score": 65,
    "ranged": true,
    "projectileType": "arrow",
    "preferEdges": true,
    "desiredRange": 360,
    "projectileCooldown": 1.5,
    "bossTier": 0,
    "preferredTarget": "player",
    "specialBehavior": [
      "mini",
      "ranged"
    ]
  },
  "miniZombie": {
    "displayName": "Zombie",
    "assetFolder": "Mini Zombie",
    "assetBaseName": "Mini Zombie",
    "health": 45,
    "maxHealth": 45,
    "damage": 5,
    "speed": 100,
    "baseRadius": 10,
    "scale": 4,
    "attackBonus": 24,
    "cooldown": 1.5,
    "score": 60,
    "ranged": false,
    "projectileType": null,
    "preferEdges": false,
    "desiredRange": 60,
    "projectileCooldown": 1.5,
    "bossTier": 0,
    "preferredTarget": "player",
    "specialBehavior": [
      "mini",
      "closestAny"
    ]
  },
  "miniZombieButcher": {
    "displayName": "Zombie Butcher",
    "assetFolder": "Mini Zombie Butcher",
    "assetBaseName": "Mini Zombie Butcher",
    "health": 45,
    "maxHealth": 45,
    "damage": 5,
    "speed": 90,
    "baseRadius": 12,
    "scale": 4,
    "attackBonus": 28,
    "cooldown": 1.7,
    "score": 65,
    "ranged": false,
    "projectileType": null,
    "preferEdges": false,
    "desiredRange": 80,
    "projectileCooldown": 1.7,
    "bossTier": 0,
    "preferredTarget": "player",
    "specialBehavior": [
      "mini",
      "closestAny"
    ]
  },
  "miniReaper": {
    "displayName": "Reaper",
    "assetFolder": "Mini Reaper",
    "assetBaseName": "Mini Reaper",
    "health": 45,
    "maxHealth": 45,
    "damage": 5,
    "speed": 120,
    "baseRadius": 11,
    "scale": 4,
    "attackBonus": 30,
    "cooldown": 1.8,
    "score": 80,
    "ranged": false,
    "projectileType": null,
    "preferEdges": false,
    "desiredRange": 90,
    "projectileCooldown": 1.8,
    "bossTier": 1,
    "preferredTarget": "player",
    "specialBehavior": [
      "mini",
      "reaper"
    ]
  },
  "miniGhost": {
    "displayName": "Ghost",
    "assetFolder": "Mini Ghost",
    "assetBaseName": "Mini Ghost",
    "health": 100,
    "maxHealth": 100,
    "damage": 20,
    "speed": 130,
    "baseRadius": 12,
    "scale": 6,
    "attackBonus": 18,
    "cooldown": 1.2,
    "score": 90,
    "ranged": false,
    "projectileType": null,
    "preferEdges": true,
    "desiredRange": 60,
    "projectileCooldown": 1.2,
    "bossTier": 0,
    "preferredTarget": "npc",
    "specialBehavior": [
      "mini",
      "targetsNPCs"
    ]
  },
  "miniLich": {
    "displayName": "Lich",
    "assetFolder": "Mini Lich",
    "assetBaseName": "Mini Lich",
    "health": 45,
    "maxHealth": 45,
    "damage": 5,
    "speed": 110,
    "baseRadius": 12,
    "scale": 4,
    "attackBonus": 24,
    "cooldown": 1.6,
    "score": 95,
    "ranged": true,
    "projectileType": "miniTrident",
    "preferEdges": true,
    "desiredRange": 420,
    "projectileCooldown": 1.6,
    "bossTier": 1,
    "preferredTarget": "player",
    "specialBehavior": [
      "mini",
      "ranged"
    ]
  },
  "miniNecromancer": {
    "displayName": "Necromancer",
    "assetFolder": "Mini Necromancer",
    "assetBaseName": "Mini Necromancer",
    "health": 50,
    "maxHealth": 50,
    "damage": 5,
    "speed": 115,
    "baseRadius": 12,
    "scale": 4,
    "attackBonus": 32,
    "cooldown": 1.8,
    "score": 120,
    "ranged": true,
    "projectileType": "miniTrident",
    "preferEdges": true,
    "desiredRange": 420,
    "projectileCooldown": 1.9,
    "bossTier": 1,
    "preferredTarget": "player",
    "specialBehavior": [
      "mini",
      "summoner"
    ]
  },
  "miniDeathKnight": {
    "displayName": "Death Knight",
    "assetFolder": "Mini Death Knight",
    "assetBaseName": "Mini Death Knight",
    "health": 60,
    "maxHealth": 60,
    "damage": 5,
    "speed": 90,
    "baseRadius": 13,
    "scale": 4,
    "attackBonus": 36,
    "cooldown": 1.8,
    "score": 140,
    "ranged": false,
    "projectileType": null,
    "preferEdges": false,
    "desiredRange": 100,
    "projectileCooldown": 1.8,
    "bossTier": 1,
    "preferredTarget": "player",
    "specialBehavior": [
      "mini",
      "heavy"
    ]
  },
  "miniDreadKnight": {
    "displayName": "Dread Knight",
    "assetFolder": "Mini Dread Knight",
    "assetBaseName": "Mini Dread Knight",
    "health": 80,
    "maxHealth": 80,
    "damage": 5,
    "speed": 85,
    "baseRadius": 15,
    "scale": 4,
    "attackBonus": 38,
    "cooldown": 1.9,
    "score": 150,
    "ranged": false,
    "projectileType": null,
    "preferEdges": false,
    "desiredRange": 110,
    "projectileCooldown": 1.9,
    "bossTier": 2,
    "preferredTarget": "player",
    "specialBehavior": [
      "mini",
      "heavy"
    ]
  },
  "miniImpLevel3": {
    "displayName": "Imp Commander",
    "assetFolder": "Mini Imp",
    "assetBaseName": "Mini Imp",
    "health": 30,
    "maxHealth": 30,
    "damage": 15,
    "speed": 80,
    "baseRadius": 10,
    "scale": 5,
    "attackBonus": 30,
    "cooldown": 0.85,
    "score": 36,
    "ranged": false,
    "projectileType": null,
    "preferEdges": false,
    "desiredRange": 36,
    "projectileCooldown": 0.85,
    "bossTier": 0,
    "preferredTarget": "player",
    "specialBehavior": [
      "mini",
      "popcorn",
      "closestAny",
      "swarmable"
    ],
    "swarmSpacing": 0.1
  }
};
  const ns =
    global.BattlechurchEnemyCatalog ||
    (global.BattlechurchEnemyCatalog = {});
  ns.catalog = ENEMY_CATALOG;
})(typeof window !== "undefined" ? window : globalThis);
