(function(global) {
  const missionBriefScenarios = [
    "deep loneliness",
    "rising anger",
    "the weight of grief",
    "destructive habits",
    "overwhelming anxiety",
    "spiritual doubt",
    "a sense of worthlessness",
    "persistent guilt",
    "old wounds resurfacing",
    "bitterness taking root",
    "the strain of burnout",
    "fear of failure",
    "shame taking hold",
    "forgiving someone close",
    "the pull of despair",
    "temptation pressing in",
    "a season of confusion",
    "broken trust",
    "loneliness after loss",
    "overwhelming stress",
    "growing discouragement",
    "the urge to withdraw",
    "resentment toward loved ones",
    "a crisis of identity",
    "unmet expectations",
    "financial pressure",
    "feeling forgotten",
    "creeping hopelessness",
    "relational conflict",
    "regret from the past",
    "fear of the future",
    "a search for purpose again",
    "the pull toward isolation",
    "intrusive negative thoughts",
    "unhealthy coping habits",
    "jealousy and comparison",
    "apathy settling in",
    "emotional exhaustion",
    "self-forgiveness",
    "emotional numbness"
  ];

  const ns = global.BattlechurchMissionBrief || (global.BattlechurchMissionBrief = {});
  ns.scenarios = missionBriefScenarios;
})(typeof window !== "undefined" ? window : globalThis);
